#!/usr/bin/env python3
"""A wizard: walks a human through a manual procedure step by step.

Generated by the /wizard skill. Standard library only, no dependencies.
Runs the same on Linux, macOS, Windows and WSL.

Everything above the "STAGES" marker is the wizard library: do not hand-edit
it. Author the per-step stages below the marker.
"""

from __future__ import annotations

import getpass
import os
import platform
import select
import shutil
import subprocess
import sys
import tempfile
import webbrowser
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

# Author sets this at the top of the stages section.
TOTAL_STAGES = 0

ENV_FILE = Path(os.environ.get("ENV_FILE", ".env"))

_stage_index = 0
_written_env: list[str] = []  # KEYs written to ENV_FILE this run
_written_secret: list[str] = []  # secret NAMEs set this run
_skipped: list[str] = []  # things we couldn't do (e.g. gh missing)
_chosen: list[tuple[str, str]] = []  # label and answer, redrawn on every stage


class Back(Exception):  # noqa: N818  a control signal, not a failure
    """Raised by choose() when the human steps back to the previous stage."""


def _enable_ansi() -> bool:
    if not sys.stdout.isatty() or os.environ.get("NO_COLOR"):
        return False
    if os.name == "nt":
        # Windows consoles need VT processing turned on before ANSI works.
        try:
            import ctypes

            kernel32 = ctypes.windll.kernel32
            handle = kernel32.GetStdHandle(-11)  # STD_OUTPUT_HANDLE
            mode = ctypes.c_uint32()
            if not kernel32.GetConsoleMode(handle, ctypes.byref(mode)):
                return False
            return bool(kernel32.SetConsoleMode(handle, mode.value | 0x4))
        except Exception:
            return False
    return True


_ANSI = _enable_ansi()


def _c(code: str) -> str:
    return code if _ANSI else ""


def _rgb(hexcode: str) -> str:
    red, green, blue = (int(hexcode[at : at + 2], 16) for at in (1, 3, 5))
    return _c(f"\033[38;2;{red};{green};{blue}m")


# Moonlight: the palette the rest of this config is themed on.
TEXT = _rgb("#ced9ff")
ACCENT = _rgb("#7386d0")
MUTED = _rgb("#aea4bf")
GOOD = _rgb("#49ef95")
ALERT = _rgb("#ca5f71")
LINK = _rgb("#5dabf3")

BOLD = _c("\033[1m")
RESET = _c("\033[0m")


def _encodable(text: str) -> bool:
    try:
        text.encode(sys.stdout.encoding or "ascii")
        return True
    except (UnicodeEncodeError, LookupError):
        return False


try:  # legacy Windows code pages can't render the glyphs below
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[union-attr]
except Exception:
    pass

_FANCY = _encodable("▸·✓⚠↗•❯")  # noqa: RUF001  the glyphs are deliberate
ARROW = "❯" if _FANCY else ">"  # noqa: RUF001  a pointer, not a quote mark
STAGE_MARK = "▸" if _FANCY else ">"
SEP = "·" if _FANCY else "-"
OK_MARK = "✓" if _FANCY else "+"
WARN_MARK = "⚠" if _FANCY else "!"
OPEN_MARK = "↗" if _FANCY else "->"
BULLET = "•" if _FANCY else "*"
TO = "→" if _FANCY else "->"
MASK = "*"  # echoed per character of a secret, so a paste is visibly the right length


def _clear() -> None:
    """Put the next thing printed at the top of the screen, keeping the history.

    Everything already printed is scrolled up rather than erased, so the stage
    on screen sits at the top while every earlier stage stays one scroll away.
    An erase would take the record of what the human chose with it.

    No-op when output isn't a terminal, so piped logs stay readable.
    """
    if not sys.stdout.isatty() or not _ANSI:
        return
    rows = shutil.get_terminal_size((80, 24)).lines
    sys.stdout.write("\n" * rows)  # pushes the screen into the scrollback
    sys.stdout.write("\033[H")  # then start again at the top of the blank view
    sys.stdout.flush()


def banner(title: str) -> None:
    """Opening frame: what this wizard does."""
    _clear()
    print(f"\n{BOLD}{ACCENT}  {title}{RESET}")
    print(f"{MUTED}  {TOTAL_STAGES} stages{RESET}\n")
    print(f"{MUTED}  You drive the browser; this wizard tells you exactly what to do and")
    print("  captures the values you copy back. Arrow keys pick from a list, and every")
    print("  answer is repeated at the top of each later stage. Left or `b` steps back")
    print("  one stage. Ctrl-C stops, though nothing already written is undone.")
    print(f"  Earlier stages stay in the scrollback.{RESET}")
    pause("Ready to start?")


def stage(name: str) -> None:
    """Announce a stage at the top of the screen, above what was chosen so far."""
    global _stage_index
    _clear()
    _stage_index += 1
    print(
        f"\n{BOLD}{ACCENT}{STAGE_MARK} Stage {_stage_index}/{TOTAL_STAGES} "
        f"{SEP} {name}{RESET}"
    )
    _recap()


def _recap() -> None:
    """Every choice made so far, so nothing has to be remembered."""
    if not _chosen:
        return
    width = max(len(prompt) for prompt, _ in _chosen)
    print(f"  {MUTED}{'chosen so far'.ljust(width)}{RESET}")
    for prompt, value in _chosen:
        print(f"  {MUTED}{prompt.ljust(width)}{RESET}  {TEXT}{value}{RESET}")
    print()


def say(text: str) -> None:
    """A plain instruction line."""
    print(f"  {text}")


def step(text: str) -> None:
    """An action the human takes in the browser."""
    print(f"  {ACCENT}{BULLET}{RESET} {text}")


def note(text: str) -> None:
    print(f"  {MUTED}{text}{RESET}")


def warn(text: str) -> None:
    print(f"  {ALERT}{WARN_MARK} {text}{RESET}")


def _is_wsl() -> bool:
    return "microsoft" in platform.uname().release.lower()


def _open_via_wsl(url: str) -> bool:
    # webbrowser doesn't know about WSL, so reach the Windows host directly.
    for exe in ("wslview", "explorer.exe"):
        path = shutil.which(exe)
        if not path:
            continue
        try:
            subprocess.run(
                [path, url],
                check=False,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
            return True
        except OSError:
            continue
    return False


def open_url(url: str) -> None:
    """Open a URL in the human's browser on any platform, WSL included."""
    print(f"  {LINK}{OPEN_MARK} opening{RESET} {url}")
    if _is_wsl() and _open_via_wsl(url):
        return
    try:
        if webbrowser.open(url):
            return
    except Exception:
        pass
    warn(f"couldn't open a browser, visit it manually: {url}")


def pause(message: str = "Press Enter to continue") -> None:
    """Wait for the human to confirm they've done the manual part."""
    global _prompted
    _prompted = True
    try:
        input(f"  {MUTED}{message}{RESET} ")
    except EOFError:
        print()


def confirm(question: str, *, back: bool = False) -> bool:
    """y/N gate. Returns True only on an explicit yes.

    With back=True, answering `b` raises Back instead, so a stage that opens
    with a confirmation can be stepped out of the same way a choose can.
    """
    global _prompted
    _prompted = True
    keys = "y/N, b to go back" if back else "y/N"
    try:
        reply = input(f"  {ACCENT}? {question} [{keys}]{RESET} ")
    except EOFError:
        print()
        return False
    answer = reply.strip().lower()
    if back and answer == "b":
        raise Back
    return answer.startswith("y")


def _read_key() -> str:
    """One keypress, normalised to 'up', 'down', 'enter' or the character itself.

    Arrow keys arrive as a two-part sequence, and the two platforms disagree on
    which: a 0xe0 prefix on Windows, an escape sequence everywhere else.
    """
    if os.name == "nt":
        import msvcrt  # Windows-only, so it can't be a module-level import

        char = msvcrt.getwch()
        if char in ("\x00", "\xe0"):
            return {"H": "up", "P": "down", "K": "left", "M": "right"}.get(
                msvcrt.getwch(), ""
            )
        if char == "\x03":
            raise KeyboardInterrupt
        return "enter" if char in ("\r", "\n") else char

    import termios  # POSIX-only, so it can't be a module-level import

    fd = sys.stdin.fileno()
    saved = termios.tcgetattr(fd)
    mode = termios.tcgetattr(fd)
    mode[3] &= ~(termios.ECHO | termios.ICANON)  # lflag
    mode[6][termios.VMIN] = 1  # cc: one character is enough to return
    mode[6][termios.VTIME] = 0
    termios.tcsetattr(fd, termios.TCSANOW, mode)
    try:
        char = _read_char(fd)
        if char == "\x03":
            raise KeyboardInterrupt
        if char in ("\r", "\n"):
            return "enter"
        if char != "\x1b":
            return char
        if not select.select([fd], [], [], 0.05)[0]:
            return "escape"
        bracket = _read_char(fd)
        code = _read_char(fd) if bracket == "[" else ""
        return {"A": "up", "B": "down", "D": "left", "C": "right"}.get(code, "")
    finally:
        termios.tcsetattr(fd, termios.TCSANOW, saved)


def _choose_typed(prompt: str, options: list[tuple[str, str]], back: bool) -> str:
    """Numbered fallback for when the terminal can't be driven key by key.

    A piped run lands here, so a scripted wizard still works: it takes the value
    or its number, and `b` when the caller allows stepping back. Two empty
    answers mean stdin has closed and looping would spin forever.
    """
    values = [value for value, _ in options]
    width = max(len(value) for value in values)
    for position, (value, description) in enumerate(options, start=1):
        print(f"  {position}. {value.ljust(width)}  {MUTED}{description}{RESET}")

    empty = 0
    while True:
        reply = _prompt(f"{prompt} [{'/'.join(values)}]", "", hidden=False).strip().lower()
        if reply in values:
            return reply
        if reply.isdigit() and 1 <= int(reply) <= len(values):
            return values[int(reply) - 1]
        if back and reply == "b":
            raise Back
        if not reply:
            empty += 1
            if empty >= 2:
                warn("no answer, and nothing left on the input")
                raise KeyboardInterrupt
        warn(f"pick one of: {', '.join(values)}")


def _remember(label: str, value: str) -> None:
    """Record an answer for the recap, replacing an earlier one for that label."""
    for position, (seen, _) in enumerate(_chosen):
        if seen == label:
            _chosen[position] = (label, value)
            return
    _chosen.append((label, value))


def choose(prompt: str, options: list[tuple[str, str]], *, back: bool = False) -> str:
    """Pick one option with the arrow keys. Returns the chosen value.

    Each option is a (value, description) pair, so the list explains itself and
    the human never has to type a word they read a line earlier. Digits jump
    straight to a row. With back=True, Left or `b` raises Back, which run_stages
    turns into a step backwards.
    """
    global _prompted
    _prompted = True
    if not (_ANSI and sys.stdin.isatty()):
        value = _choose_typed(prompt, options, back)
        _remember(prompt, value)
        return value

    width = max(len(value) for value, _ in options)
    index = 0

    def render(again: bool) -> None:
        if again:
            sys.stdout.write(f"\033[{len(options)}A")
        for position, (value, description) in enumerate(options):
            chosen = position == index
            marker = f"{ACCENT}{ARROW}{RESET}" if chosen else " "
            label = value.ljust(width)
            label = f"{BOLD}{label}{RESET}" if chosen else label
            sys.stdout.write(f"\r\033[K  {marker} {label}  {MUTED}{description}{RESET}\n")
        sys.stdout.flush()

    hint = "arrows, then Enter" + (", or Left to go back a stage" if back else "")
    print(f"\n  {BOLD}{prompt}{RESET} {MUTED}{hint}{RESET}")
    sys.stdout.write("\033[?25l")  # the cursor parked mid-list reads as a glitch
    stepped_back = False
    try:
        render(again=False)
        while True:
            pressed = _read_key()
            if pressed == "enter":
                break
            if back and pressed in ("left", "b"):
                stepped_back = True
                break
            if pressed in ("up", "k"):
                index = (index - 1) % len(options)
            elif pressed in ("down", "j"):
                index = (index + 1) % len(options)
            elif pressed.isdigit() and 1 <= int(pressed) <= len(options):
                index = int(pressed) - 1
                render(again=True)
                break
            else:
                continue
            render(again=True)
    finally:
        sys.stdout.write("\033[?25h")
        sys.stdout.flush()

    if stepped_back:
        raise Back

    value = options[index][0]
    print(f"  {GOOD}{OK_MARK}{RESET} {value}")
    _remember(prompt, value)
    return value


_planned: list[tuple[int, str, callable]] = []  # stage, receipt line, action
_approved = False
_prompted = False  # did the running stage ask the human anything


def plan(line: str, action: callable) -> None:
    """Queue a side effect for after the receipt, instead of doing it now.

    Stages only ask and look; every download, write and copy goes through here,
    so the human sees the whole list and says yes once before anything changes.
    `line` is exactly what the receipt prints for it.
    """
    _planned.append((_stage_index, line, action))


def receipt() -> None:
    """The last stage: every answer and every queued action, one confirmation."""
    global _approved
    stage("Receipt")
    if not _planned:
        say("Nothing to do: everything is already in place.")
        _approved = False
        return

    say("About to:")
    for _, line, _ in _planned:
        print(f"  {ACCENT}{BULLET}{RESET} {line}")
    print()
    note("Nothing has been downloaded, written or copied yet.")
    _approved = confirm("Do all of the above?", back=True)


def apply() -> None:
    """Run the queued actions in order. A failure is reported and the rest go on."""
    _clear()
    print(f"\n{BOLD}{ACCENT}{STAGE_MARK} Applying{RESET}\n")
    for _, line, action in _planned:
        print(f"  {ACCENT}{ARROW}{RESET} {line}")
        try:
            action()
        except Exception as error:  # noqa: BLE001  one failure must not stop the rest
            warn(f"failed: {error}")
            _skipped.append(line)
        print()


def run_stages(stages: list[callable]) -> None:
    """Run the stages in order, letting a Back signal re-open the one before.

    Back lands on the nearest earlier stage that actually asked something: one
    that only looked at the disk would run straight through and bounce the human
    forward again. Re-entering a stage drops what it and every later stage had
    planned, so a changed answer cannot leave a stale action in the receipt.
    """
    global _stage_index, _prompted
    asked = [False] * len(stages)
    index = 0
    while index < len(stages):
        _stage_index = index  # so a step back renumbers instead of counting on
        # plans carry the 1-based number stage() assigns, so this keeps earlier stages only
        _planned[:] = [entry for entry in _planned if entry[0] <= index]
        _prompted = False
        try:
            stages[index]()
        except Back:
            target = index - 1
            while target > 0 and not asked[target]:
                target -= 1
            index = max(target, 0)
            continue
        asked[index] = _prompted
        index += 1


def _existing(key: str) -> str:
    """Current value of key in ENV_FILE, if any."""
    if not ENV_FILE.is_file():
        return ""
    value = ""
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        if line.startswith(f"{key}="):
            value = line.split("=", 1)[1]
    return value


def _read_char(fd: int) -> str:
    """Read one character straight off the descriptor.

    sys.stdin.read(1) can block waiting to fill its buffer, which stalls
    character-at-a-time input, so go to the descriptor and rebuild multi-byte
    UTF-8 by hand.
    """
    data = os.read(fd, 1)
    while data:
        try:
            return data.decode("utf-8")
        except UnicodeDecodeError:
            if len(data) >= 4:
                return ""
            data += os.read(fd, 1)
    return ""


def _drain_escape(fd: int) -> None:
    """Swallow the rest of an escape sequence (arrow keys, Home, etc.)."""
    while select.select([fd], [], [], 0.002)[0]:
        os.read(fd, 1)


def _read_masked(label: str) -> str:
    """Read a secret, echoing one MASK per character.

    Full invisibility makes it impossible to tell a paste landed, landed twice,
    or landed empty, so we show the length without showing the value. Falls back
    to getpass when stdin isn't a terminal (piped input, CI).
    """
    if not sys.stdin.isatty():
        return getpass.getpass(label)

    chars: list[str] = []

    def _backspace() -> None:
        if chars:
            chars.pop()
            sys.stdout.write("\b \b")

    def _show(text: str) -> None:
        sys.stdout.write(text)
        sys.stdout.flush()

    if os.name == "nt":
        import msvcrt  # Windows-only, so it can't be a module-level import

        _show(label)
        while True:
            char = msvcrt.getwch()
            if char in ("\r", "\n"):
                break
            if char == "\x03":
                raise KeyboardInterrupt
            if char in ("\b", "\x7f"):
                _backspace()
            elif char in ("\x00", "\xe0"):
                msvcrt.getwch()  # discard the second half of a special key
            elif char >= " ":
                chars.append(char)
                sys.stdout.write(MASK)
            sys.stdout.flush()
    else:
        import termios  # POSIX-only, so it can't be a module-level import

        fd = sys.stdin.fileno()
        saved = termios.tcgetattr(fd)
        mode = termios.tcgetattr(fd)
        mode[3] &= ~(termios.ECHO | termios.ICANON)  # lflag
        mode[6][termios.VMIN] = 1  # cc: one character is enough to return
        mode[6][termios.VTIME] = 0
        # TCSANOW, never TCSAFLUSH: flushing discards whatever the human already
        # pasted, and draining stalls until pending output is consumed. Both open
        # a window where the terminal still echoes the secret in cleartext.
        termios.tcsetattr(fd, termios.TCSANOW, mode)
        try:
            # Prompt goes out only after echo is off, so no keystroke can leak.
            _show(label)
            while True:
                char = _read_char(fd)
                if char in ("\r", "\n", ""):
                    break
                if char == "\x03":
                    raise KeyboardInterrupt
                if char in ("\x7f", "\b"):
                    _backspace()
                elif char == "\x15":  # Ctrl-U wipes the line
                    while chars:
                        _backspace()
                elif char == "\x04":  # Ctrl-D
                    break
                elif char == "\x1b":
                    _drain_escape(fd)
                elif char >= " ":
                    chars.append(char)
                    sys.stdout.write(MASK)
                sys.stdout.flush()
        finally:
            termios.tcsetattr(fd, termios.TCSANOW, saved)

    print()
    return "".join(chars)


def _prompt(prompt: str, current: str, hidden: bool) -> str:
    global _prompted
    _prompted = True
    suffix = f" {MUTED}[Enter keeps current]{RESET}" if current else ""
    label = f"  {BOLD}{prompt}{RESET}{suffix} "
    try:
        value = _read_masked(label) if hidden else input(label)
    except EOFError:
        print()
        value = ""
    return value.strip() or current


def ask(key: str, prompt: str) -> str:
    """Read a visible (non-secret) value.

    Offers the existing ENV_FILE value as a default on re-runs, so Enter keeps
    it, and joins the recap under a label built from the key. Secrets never do:
    that is what ask_secret is for.
    """
    value = _prompt(prompt, _existing(key), hidden=False)
    if value:
        _remember(key.lower().replace("_", " "), value)
    return value


def ask_secret(key: str, prompt: str) -> str:
    """Like ask, but each character echoes as MASK instead of the value."""
    return _prompt(prompt, _existing(key), hidden=True)


_env_checked = False


def _warn_if_env_tracked() -> None:
    """Warn once when ENV_FILE isn't git-ignored, since secrets land in it."""
    global _env_checked
    if _env_checked or not shutil.which("git"):
        return
    _env_checked = True
    done = subprocess.run(
        ["git", "check-ignore", "-q", str(ENV_FILE)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if done.returncode == 1:  # 0 = ignored, 128 = not a git repo
        warn(f"{ENV_FILE} is not git-ignored. Add it to .gitignore before committing")


def write_env(key: str, value: str) -> None:
    """Upsert key=value into ENV_FILE, creating it if needed. Idempotent.

    Written 0600 and swapped in atomically, so a crash can neither truncate the
    real file nor leave a copy of the value behind in a temp file.
    """
    _warn_if_env_tracked()
    lines = (
        ENV_FILE.read_text(encoding="utf-8").splitlines()
        if ENV_FILE.is_file()
        else []
    )
    kept = [line for line in lines if not line.startswith(f"{key}=")]
    kept.append(f"{key}={value}")

    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    handle, tmp = tempfile.mkstemp(dir=str(ENV_FILE.parent or "."))
    try:
        with os.fdopen(handle, "w", encoding="utf-8", newline="\n") as out:
            out.write("\n".join(kept) + "\n")
        if os.name != "nt":
            os.chmod(tmp, 0o600)
        os.replace(tmp, ENV_FILE)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise

    if key not in _written_env:
        _written_env.append(key)
    print(f"  {GOOD}{OK_MARK} wrote{RESET} {key} {TO} {ENV_FILE}")


def _gh_ready() -> bool:
    if not shutil.which("gh"):
        return False
    done = subprocess.run(
        ["gh", "auth", "status"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    return done.returncode == 0


def set_secret(name: str, value: str) -> None:
    """Set a GitHub Actions repo secret via gh, passing the value over stdin.

    Records a manual to-do instead of failing when gh is missing or logged out.
    """
    if _gh_ready():
        done = subprocess.run(
            ["gh", "secret", "set", name],
            input=value,
            text=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if done.returncode == 0:
            _written_secret.append(name)
            print(f"  {GOOD}{OK_MARK} set{RESET} GitHub secret {name}")
            return
    _skipped.append(f"GitHub secret {name} (set it manually: gh secret set {name})")
    warn(f"skipped GitHub secret {name}, gh not ready. Set it later")


def set_var(name: str, value: str) -> None:
    """Set a GitHub Actions repo variable. Non-secret values only.

    Sent over stdin like set_secret, so the value never appears in the process
    list or the shell history. Anything secret belongs in set_secret.
    """
    if _gh_ready():
        done = subprocess.run(
            ["gh", "variable", "set", name],  # no --body: gh reads stdin
            input=value,
            text=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if done.returncode == 0:
            print(f"  {GOOD}{OK_MARK} set{RESET} GitHub variable {name}")
            return
    _skipped.append(f"GitHub variable {name}")
    warn(f"skipped GitHub variable {name}, gh not ready. Set it later")


def finish() -> None:
    """Clear, then a closing summary of everything configured."""
    _clear()
    print(f"\n{BOLD}{GOOD}  {OK_MARK} Setup complete{RESET}")
    if _written_env:
        note(
            f"wrote {len(_written_env)} value(s) to {ENV_FILE}: "
            f"{' '.join(_written_env)}"
        )
    if _written_secret:
        note(
            f"set {len(_written_secret)} GitHub secret(s): "
            f"{' '.join(_written_secret)}"
        )
    if _skipped:
        print()
        warn("still to do by hand:")
        for item in _skipped:
            note(f"  - {item}")
    print()


def run(main: callable) -> None:
    """Entry point: runs the stages, exits cleanly on Ctrl-C."""
    try:
        main()
    except KeyboardInterrupt:
        print(
            f"\n  {MUTED}stopped. Re-running starts at stage 1 again, but values "
            f"already saved come back as defaults, so Enter skips through them.{RESET}\n"
        )
        sys.exit(130)


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

import json
import re
import urllib.error
import urllib.request
import zipfile

TOTAL_STAGES = 9

REPO = Path(__file__).resolve().parent
CONFIG = REPO / "portable_config"
UOSC_DIR = CONFIG / "scripts" / "uosc"
SHADERS = CONFIG / "shaders"
ANIME4K = SHADERS / "Anime4K"
ANILIST_DIR = CONFIG / "scripts" / "anilistUpdater"
VENDOR = ANILIST_DIR / "vendor"
LAYOUT_CONF = CONFIG / "script-opts" / "keybind-visualizer.conf"
APPLY_PATCH = REPO / "patches" / "apply.py"

# Every URL below comes from the README, from mpv.io or from the upstream
# project's own instructions. None is assembled here.
MPV_PAGE = "https://mpv.io/installation/"
UOSC_REPO = "tomasklaen/uosc"
ANIME4K_REPO = "bloc97/Anime4K"
UOSC_PAGE = f"https://github.com/{UOSC_REPO}/releases/latest"
ANIME4K_PAGE = f"https://github.com/{ANIME4K_REPO}/releases/latest"
FFMPEG_PAGE = "https://ffmpeg.org/download.html"
UV_PAGE = "https://github.com/astral-sh/uv"
# AzuredBlue's README hands out this client id, so there is no client to create.
ANILIST_AUTH = "https://anilist.co/api/v2/oauth/authorize?client_id=20740&response_type=token"

# mpv.io: "All binary packages are unofficial third-party builds, except as
# noted." These are the two it lists that ship normal GitHub releases.
MPV_BUILDS = (
    ("shinchiro", "shinchiro/mpv-winbuild-cmake"),
    ("zhongfly", "zhongfly/mpv-winbuild"),
)

# What one stage worked out and a later one needs. A plain module dict rather
# than arguments, since run_stages can re-enter any stage on its own.
FOUND: dict[str, Path | str | bool | None] = {"mpv": None, "home": None, "installed": None}

LAYOUTS = [
    ("ansi", "US and most of the world, single-row Enter"),
    ("iso", "UK and most of Europe, tall Enter, extra key by Z"),
    ("abnt2", "Brazilian, extra key by the right Shift"),
    ("jis", "Japanese"),
]

# platform.machine() spelling on the left, the token these builds use on the right.
ARCHES = {
    "AMD64": "x86_64",
    "x86_64": "x86_64",
    "ARM64": "aarch64",
    "aarch64": "aarch64",
    "x86": "i686",
    "i686": "i686",
}
SHADER_REF = re.compile(r"~~/shaders/([A-Za-z0-9_./-]+\.(?:glsl|hook))")


def have(exe: str) -> str:
    return shutil.which(exe) or ""


def run_cmd(args: list[str], cwd: Path | None = None) -> bool:
    sys.stdout.flush()  # or the child's output lands ahead of ours in a pipe
    try:
        done = subprocess.run(args, cwd=str(cwd) if cwd else None, check=False)
    except OSError as error:
        warn(f"could not run {args[0]}: {error}")
        return False
    return done.returncode == 0


def capture(args: list[str], stdin_text: str | None = None) -> tuple[bool, list[str]]:
    """Run a command and hand back its stdout lines. Never echoes stdin."""
    try:
        done = subprocess.run(
            args,
            input=stdin_text,
            text=True,
            capture_output=True,
            check=False,
        )
    except OSError as error:
        return False, [str(error)]
    return done.returncode == 0, (done.stdout + done.stderr).splitlines()


def ask_path(key: str, prompt: str) -> Path | None:
    """Read a filesystem path, resolving the quotes a paste brings and any ~."""
    raw = ask(key, prompt).strip().strip('"').strip("'")
    if not raw:
        return None
    return Path(os.path.expandvars(raw)).expanduser()


def https_request(url: str, accept: str = "*/*") -> urllib.request.Request:
    """Build a request, refusing any scheme but https.

    Download URLs arrive from a GitHub API response rather than from this file,
    so the scheme is checked here instead of trusted.
    """
    if not url.startswith("https://"):
        raise ValueError(f"refusing a URL that is not https: {url}")
    return urllib.request.Request(  # noqa: S310  the scheme is enforced above
        url,
        headers={"User-Agent": "moonlight-mpv-first-run", "Accept": accept},
    )


def fetch_json(url: str) -> dict:
    request = https_request(url, "application/vnd.github+json")
    with urllib.request.urlopen(request, timeout=20) as response:  # noqa: S310  scheme checked above
        return json.load(response)


def latest_release(repo: str) -> tuple[str, list[tuple[str, str]]]:
    """Tag, then the name and download URL of every asset on it.

    Names are read off the release rather than guessed, since they carry a
    version, a build date and a commit hash that nothing here could reconstruct.
    """
    try:
        payload = fetch_json(f"https://api.github.com/repos/{repo}/releases/latest")
    except (urllib.error.URLError, OSError, ValueError) as error:
        warn(f"could not reach the GitHub API for {repo}: {error}")
        return "", []
    return payload.get("tag_name", ""), [
        (asset["name"], asset["browser_download_url"])
        for asset in payload.get("assets", [])
        if asset.get("name") and asset.get("browser_download_url")
    ]


def latest_assets(repo: str) -> list[tuple[str, str]]:
    return latest_release(repo)[1]


def pick_build(assets: list[tuple[str, str]]) -> tuple[str, str] | None:
    """The one build on a release that fits the machine running this.

    These releases carry a dozen archives: three architectures, each with a
    debug and a headers-only variant, plus ffmpeg on its own. Only one of them
    is the player for this CPU, so the human is never asked to tell them apart.
    """
    arch = ARCHES.get(platform.machine(), "")
    if not arch:
        warn(f"no build matches {platform.machine()}")
        return None

    fitting = [
        (name, url)
        for name, url in assets
        if name.lower().startswith("mpv-")
        and f"-{arch}-" in name
        and not any(skip in name for skip in ("-dev-", "-debug-", "-lgpl-"))
    ]
    # A -v3 build needs AVX2, which a CPU older than roughly 2014 lacks, so the
    # plain one is the only safe automatic pick.
    fitting.sort(key=lambda asset: ("-v3-" in asset[0], asset[0]))
    return fitting[0] if fitting else None


def unpack(archive: Path, dest: Path) -> bool:
    if archive.suffix.lower() == ".zip":
        try:
            with zipfile.ZipFile(archive) as zipped:
                zipped.extractall(dest)
        except (zipfile.BadZipFile, OSError) as error:
            warn(f"could not unpack {archive.name}: {error}")
            return False
        return True
    return unpack_7z(archive, dest)


def unpack_7z(archive: Path, dest: Path) -> bool:
    """Unpack a .7z with whatever the machine already has.

    Windows ships bsdtar, whose libarchive reads 7-Zip, so nothing has to be
    installed. It is addressed by full path on purpose: a `tar` earlier in PATH
    is usually GNU tar, which cannot read the format and fails confusingly.
    """
    attempts = []
    bsdtar = Path(os.environ.get("SYSTEMROOT", r"C:\Windows")) / "System32" / "tar.exe"
    if bsdtar.is_file():
        attempts.append([str(bsdtar), "-xf", str(archive), "-C", str(dest)])
    for exe in ("7z", "7za", "7zz"):
        found = have(exe)
        if found:
            attempts.append([found, "x", f"-o{dest}", "-y", str(archive)])

    for command in attempts:
        ok, output = capture(command)
        if ok:
            return True
        note(f"{Path(command[0]).name} could not read it: {' '.join(output[-1:])}")

    warn("nothing on this machine can unpack a .7z")
    note("Windows 10 and later ship one at System32\\tar.exe; otherwise install 7-Zip.")
    return False


def download(url: str, dest: Path) -> bool:
    say(f"downloading {dest.name}")
    try:
        request = https_request(url)
        with urllib.request.urlopen(request, timeout=60) as response, dest.open("wb") as out:  # noqa: S310  scheme checked in https_request
            shutil.copyfileobj(response, out)
    except (urllib.error.URLError, OSError, ValueError) as error:
        warn(f"download failed: {error}")
        dest.unlink(missing_ok=True)
        return False
    return True


def zip_members_under(archive: zipfile.ZipFile, marker: str) -> list[str]:
    """Members sitting under `marker`, wherever the archive roots that folder."""
    marker = marker.strip("/") + "/"
    return [name for name in archive.namelist() if marker in name.replace("\\", "/")]


def extract_subtree(zip_path: Path, marker: str, dest: Path) -> bool:
    """Copy one subtree out of a zip into dest, flattening the archive's prefix."""
    try:
        with zipfile.ZipFile(zip_path) as archive:
            members = zip_members_under(archive, marker)
            if not members:
                warn(f"{zip_path.name} has no {marker}/ inside it")
                note("top level of the archive: " + ", ".join(sorted(
                    {name.replace("\\", "/").split("/")[0] for name in archive.namelist()}
                )))
                return False
            marker_slash = marker.strip("/") + "/"
            for name in members:
                clean = name.replace("\\", "/")
                relative = clean.split(marker_slash, 1)[1]
                if not relative or clean.endswith("/"):
                    continue
                target = dest / relative
                target.parent.mkdir(parents=True, exist_ok=True)
                with archive.open(name) as source, target.open("wb") as out:
                    shutil.copyfileobj(source, out)
    except (zipfile.BadZipFile, OSError) as error:
        warn(f"could not read {zip_path}: {error}")
        return False
    return True


def extract_pattern(zip_path: Path, suffixes: tuple[str, ...], dest: Path) -> int:
    """Extract every file with one of these suffixes, flat, into dest."""
    count = 0
    try:
        with zipfile.ZipFile(zip_path) as archive:
            dest.mkdir(parents=True, exist_ok=True)
            for name in archive.namelist():
                if name.endswith("/") or not name.lower().endswith(suffixes):
                    continue
                target = dest / Path(name.replace("\\", "/")).name
                with archive.open(name) as source, target.open("wb") as out:
                    shutil.copyfileobj(source, out)
                count += 1
    except (zipfile.BadZipFile, OSError) as error:
        warn(f"could not read {zip_path}: {error}")
        return 0
    return count


def referenced_shaders() -> set[str]:
    """Every shader path input.conf and profiles.conf actually load."""
    found: set[str] = set()
    for name in ("input.conf", "profiles.conf", "mpv.conf"):
        path = CONFIG / name
        if not path.is_file():
            continue
        for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
            if line.lstrip().startswith("#"):  # commented-out bindings load nothing
                continue
            found.update(SHADER_REF.findall(line))
    return found


def set_conf_option(path: Path, key: str, value: str) -> None:
    """Upsert `key=value` in an mpv script-opts file, leaving comments alone."""
    lines = path.read_text(encoding="utf-8").splitlines() if path.is_file() else []
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=")
    replaced = False
    for index, line in enumerate(lines):
        if pattern.match(line):
            lines[index] = f"{key}={value}"
            replaced = True
    if not replaced:
        lines.append(f"{key}={value}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"  {GOOD}{OK_MARK} set{RESET} {key}={value} {TO} {path.name}")


def find_mpv() -> Path | None:
    on_path = have("mpv")
    if on_path:
        return Path(on_path)
    # The build SVP ships is where this config grew up, so it is worth a look.
    for candidate in (
        Path(os.environ.get("PROGRAMFILES(X86)", r"C:\Program Files (x86)"))
        / "SVP 4" / "mpv64" / "mpv.exe",
        Path(os.environ.get("PROGRAMFILES", r"C:\Program Files")) / "mpv" / "mpv.exe",
    ):
        if candidate.is_file():
            return candidate
    return None


def current_layout() -> str:
    if not LAYOUT_CONF.is_file():
        return ""
    for line in LAYOUT_CONF.read_text(encoding="utf-8").splitlines():
        found = re.match(r"^\s*layout\s*=\s*(\S+)", line)
        if found:
            return found.group(1)
    return ""


def release_zip(repo: str, hint: str) -> tuple[str, str, str] | None:
    """Tag, name and URL of the one zip on a repo's latest release, or None."""
    tag, assets = latest_release(repo)
    zips = [
        (name, url)
        for name, url in assets
        if name.lower().endswith(".zip") and hint.lower() in name.lower()
    ]
    if not zips:
        return None
    return tag, zips[0][0], zips[0][1]


def find_build() -> tuple[str, str, str] | None:
    """Repo, asset name and URL of the build for this machine.

    The sources are tried in the order mpv.io lists them, so a release that is
    mid-upload or missing an architecture falls through to the next rather than
    dead-ending the wizard.
    """
    for _, repo in MPV_BUILDS:
        picked = pick_build(latest_assets(repo))
        if picked:
            return repo, picked[0], picked[1]
    return None


# ── Stages: each one looks and asks. Every change is a plan(), run after the receipt.


def report_tools() -> None:
    for exe, why in (
        ("ffmpeg", "F4 subtitle index, subtitle export, chapter remux"),
        ("uv", "installs the AniList python packages, `just setup`"),
        ("just", "the repo's recipes; this wizard runs their commands directly"),
        ("git", "only needed to pull updates"),
    ):
        if have(exe):
            print(f"  {GOOD}{OK_MARK}{RESET} {exe}")
        else:
            warn(f"{exe} missing {SEP} {why}")

    if not have("ffmpeg"):
        note(f"ffmpeg is the one that silently breaks features: {FFMPEG_PAGE}")
    if not have("uv"):
        note(f"uv: {UV_PAGE}. Without it the AniList packages come through pip.")


def stage_prerequisites() -> None:
    """Settle the mpv to launch and the folder the config gets installed into.

    Those are one folder for a normal install and deliberately different for a
    portable one aimed at an empty directory, where an already installed mpv is
    pointed at the new config with --config-dir.
    """
    stage("Prerequisites and install location")
    say("Checking the tools the config and its scripts shell out to.")
    print()
    report_tools()
    print()

    say("Where the config gets installed.")
    mode = choose(
        "Install",
        [
            ("here", "mpv into this repo folder, so nothing is ever copied"),
            ("system", "beside the mpv you already have"),
            ("portable", "into a folder you name, touching nothing else"),
        ],
    )
    FOUND["mode"] = mode
    if mode == "here":
        locate_here()
    elif mode == "portable":
        locate_portable()
    else:
        locate_system()


def locate_here() -> None:
    print()
    say(f"mpv goes into {REPO}, next to the portable_config already there.")
    note("Nothing gets copied, and repo edits take effect at once.")
    FOUND["home"] = REPO

    inside = REPO / "mpv.exe"
    if inside.is_file():
        say(f"already there: {inside}")
        FOUND["mpv"] = inside
        return
    if not plan_mpv_fetch(REPO):
        warn("without an mpv in the repo folder the config cannot be read from here")
        note("Re-run and pick system or portable, or drop an mpv build into the folder.")


def locate_system() -> None:
    mpv = find_mpv()
    if mpv:
        print()
        say(f"found mpv at {mpv}")
        if confirm("Use this one?"):
            FOUND["mpv"], FOUND["home"] = mpv, mpv.parent
            return
    obtain_mpv()


def locate_portable() -> None:
    print()
    home = ask_path("MPV_HOME", "Folder to install into (created if missing):")
    if home is None:
        _skipped.append("everything downstream: no install folder given")
        return
    FOUND["home"] = home
    if not home.exists():
        plan(f"create {home}", lambda: home.mkdir(parents=True, exist_ok=True))

    inside = home / "mpv.exe"
    if inside.is_file():
        say(f"mpv is already in that folder: {inside}")
        FOUND["mpv"] = inside
        return

    print()
    say(f"{home} has no mpv.exe of its own.")
    route = choose(
        "That folder",
        [
            ("fetch", "download a build into it, so it stands alone"),
            ("borrow", "config only, launched by an mpv you already have"),
        ],
    )
    if route == "fetch":
        if plan_mpv_fetch(home):
            return
        warn("nothing to fetch, falling back to borrowing one")

    FOUND["mpv"] = find_mpv() or ask_existing_mpv()
    if FOUND["mpv"]:
        note(f"the launch at the end points {FOUND['mpv'].name} at this folder with --config-dir.")


def obtain_mpv() -> None:
    """No mpv was found: fetch one, be told where one is, or go and install it."""
    print()
    warn("mpv itself is not part of this repo, and could not be found.")
    note("On Windows mpv has no official binary: mpv.io calls every Windows")
    note("package an unofficial third-party build, so fetch takes the one it")
    note("lists first, matched to this CPU.")
    route = choose(
        "Get mpv",
        [
            ("fetch", "download it now, nothing to choose"),
            ("have", "you have it already, and will give me the path"),
            ("page", "open mpv.io and install it yourself"),
        ],
    )

    if route == "fetch":
        target = ask_path("MPV_HOME", "Folder to install mpv into:")
        if target is not None and plan_mpv_fetch(target):
            FOUND["home"] = target
            return
        warn("nothing to fetch, so point me at one instead")

    if route == "page":
        open_url(MPV_PAGE)
        pause("Install or extract mpv, then press Enter")

    mpv = ask_existing_mpv()
    FOUND["mpv"] = mpv
    FOUND["home"] = mpv.parent if mpv else None


def ask_existing_mpv() -> Path | None:
    while True:
        given = ask_path("MPV_EXE", "Path to mpv.exe (or the folder holding it):")
        if given is None:
            _skipped.append("everything downstream: no mpv path given")
            return None
        candidate = given / "mpv.exe" if given.is_dir() else given
        if candidate.is_file():
            return candidate
        warn(f"no mpv executable at {candidate}")


def plan_mpv_fetch(target: Path) -> bool:
    """Resolve the build now, so the receipt can name it, and queue the download."""
    if os.name != "nt":
        warn("this only downloads Windows builds; elsewhere use your package manager")
        note("mpv is packaged for every major distribution and for Homebrew.")
        return False

    say(f"looking for a {ARCHES.get(platform.machine(), platform.machine())} build")
    found = find_build()
    if found is None:
        warn("no release currently carries a build for this machine")
        return False
    repo, name, url = found
    say(f"{name} from github.com/{repo}")

    def action() -> None:
        FOUND["mpv"] = unpack_mpv(name, url, target)

    plan(f"download {name} into {target}", action)
    return True


def unpack_mpv(name: str, url: str, target: Path) -> Path | None:
    target.mkdir(parents=True, exist_ok=True)
    archive = target / name
    if not download(url, archive):
        return None
    try:
        if not unpack(archive, target):
            return None
    finally:
        archive.unlink(missing_ok=True)

    found = next(target.rglob("mpv.exe"), None)
    if found is None:
        warn(f"{name} unpacked but holds no mpv.exe")
        return None
    print(f"  {GOOD}{OK_MARK} unpacked{RESET} mpv {TO} {found}")
    return found


def stage_uosc() -> None:
    stage("uosc")
    say("uosc is taken from upstream rather than committed, and it is the")
    say("interface: without it there is no timeline, no menu and no controls.")
    print()

    if (UOSC_DIR / "main.lua").is_file():
        say(f"already present at {UOSC_DIR}")
        if not confirm("Replace it with a fresh download?", back=True):
            return

    found = release_zip(UOSC_REPO, "uosc")
    if found is None:
        warn("could not resolve the uosc release, so you will be asked for the zip")
        plan("install uosc from a zip you download yourself", install_uosc_by_hand)
    else:
        tag, name, url = found
        say(f"{name} from github.com/{UOSC_REPO} {tag}")
        plan(f"download uosc {tag} into scripts/uosc/", lambda name=name, url=url: install_uosc(name, url))
    FOUND["uosc_planned"] = True


def install_uosc(name: str, url: str) -> None:
    archive = Path(tempfile.mkdtemp(prefix="first-run-")) / name
    try:
        if not download(url, archive):
            _skipped.append(f"install uosc into {UOSC_DIR}")
            return
        unpack_uosc(archive)
    finally:
        shutil.rmtree(archive.parent, ignore_errors=True)


def unpack_uosc(archive: Path) -> None:
    if UOSC_DIR.exists():
        shutil.rmtree(UOSC_DIR, ignore_errors=True)
    UOSC_DIR.mkdir(parents=True, exist_ok=True)
    if extract_subtree(archive, "scripts/uosc", UOSC_DIR):
        print(f"  {GOOD}{OK_MARK} unpacked{RESET} uosc {TO} {UOSC_DIR}")
        note("Its two fonts are skipped: this repo ships them in fonts/ already.")
    else:
        _skipped.append(f"install uosc into {UOSC_DIR}")


def install_uosc_by_hand() -> None:
    """Fallback for a machine that cannot reach the GitHub API."""
    open_url(UOSC_PAGE)
    step("Download uosc.zip from the release assets, and leave it zipped.")
    archive = ask_path("UOSC_ZIP", "Path to the downloaded uosc.zip:")
    if archive is None or not archive.is_file():
        warn("no archive given, skipping")
        _skipped.append(f"install uosc into {UOSC_DIR}")
        return
    unpack_uosc(archive)


def stage_patch() -> None:
    stage("Cascade menu patch")
    say("uosc slides its whole menu stack to centre the current level. The local")
    say("patch pins the root where you clicked and cascades submenus rightwards.")
    print()

    installed = (UOSC_DIR / "main.lua").is_file()
    if not installed and not FOUND.get("uosc_planned"):
        warn("uosc is neither installed nor planned, so there is nothing to patch")
        _skipped.append("run `just patch` once uosc is installed")
        return

    if installed and not FOUND.get("uosc_planned"):
        ok, lines = capture([sys.executable, str(APPLY_PATCH), "--check"])
        if ok and any("already applied" in line for line in lines):
            say("already applied, nothing to do")
            return

    say("applied once uosc is in place")
    plan("apply the cascade menu patch to uosc", apply_patch)


def apply_patch() -> None:
    if run_cmd([sys.executable, str(APPLY_PATCH)]):
        print(f"  {GOOD}{OK_MARK} patched{RESET} uosc")
        note("uosc's own updater overwrites this. Run `just patch` after every update.")
        return
    warn("the patch did not apply cleanly")
    note("uosc moved the lines it anchors on. Open patches/uosc-cascade-menu.patch")
    note("against the installed uosc and re-anchor the hunks.")
    _skipped.append("reapply patches/uosc-cascade-menu.patch by hand")


def stage_shaders() -> None:
    stage("Anime4K shaders")
    say("Shaders are too large to commit. profiles.conf and the CTRL+1..7")
    say("bindings load them from shaders/Anime4K/, so the folder name matters.")
    print()

    wanted = referenced_shaders()
    missing = sorted(name for name in wanted if not (SHADERS / name).is_file())
    anime = [name for name in missing if name.startswith("Anime4K/")]
    others = [name for name in missing if not name.startswith("Anime4K/")]
    say(f"{len(wanted) - len(missing)} of {len(wanted)} shaders this config loads are present")

    if anime:
        found = release_zip(ANIME4K_REPO, "anime4k")
        if found is None:
            warn("could not resolve the Anime4K release, so you will be asked for the zip")
            plan("install Anime4K from a zip you download yourself", install_anime4k_by_hand)
        else:
            tag, name, url = found
            say(f"{name} from github.com/{ANIME4K_REPO} {tag} covers {len(anime)} of the missing")
            plan(f"download Anime4K {tag} into shaders/Anime4K/", lambda name=name, url=url: install_anime4k(name, url))

    if others:
        warn("in no release, so these stay missing:")
        for shader in others:
            note(f"  {shader}")
        note("shaders_list.txt names every one I use; these come from scattered gists.")
        _skipped.append(f"{len(others)} shader file(s) to fetch by hand under {SHADERS}")


def install_anime4k(name: str, url: str) -> None:
    archive = Path(tempfile.mkdtemp(prefix="first-run-")) / name
    try:
        if download(url, archive):
            report_shaders(extract_pattern(archive, (".glsl", ".hook"), ANIME4K))
    finally:
        shutil.rmtree(archive.parent, ignore_errors=True)


def install_anime4k_by_hand() -> None:
    """Fallback for a machine that cannot reach the GitHub API."""
    open_url(ANIME4K_PAGE)
    step("Download the Anime4K zip from the release assets.")
    archive = ask_path("ANIME4K_ZIP", "Path to the downloaded Anime4K zip:")
    if archive is None or not archive.is_file():
        warn("no archive given")
        return
    report_shaders(extract_pattern(archive, (".glsl", ".hook"), ANIME4K))


def report_shaders(count: int) -> None:
    if count:
        print(f"  {GOOD}{OK_MARK} unpacked{RESET} {count} shader(s) {TO} {ANIME4K}")
    else:
        _skipped.append(f"Anime4K shaders into {ANIME4K}")


def stage_layout() -> None:
    stage("Keyboard layout")
    say("mpv cannot read the OS keyboard layout, so F6 draws whichever one this")
    say("file names. It ships set to abnt2, which is a Brazilian keyboard.")
    layout = choose("Your keyboard", LAYOUTS, back=True)
    if layout == current_layout():
        say(f"already set to {layout}")
        return
    plan(
        f"set layout={layout} in script-opts/keybind-visualizer.conf",
        lambda: set_conf_option(LAYOUT_CONF, "layout", layout),
    )
    note("That edits the repo's tracked copy, so it turns up in `git status`.")


def stage_anilist_deps() -> None:
    stage("AniList python packages")
    say("The AniList scripts import requests and guessit. They go into a local")
    say("vendor/ folder, so they do not depend on whatever Lib sits beside mpv.")
    print()

    ok, _ = capture([sys.executable, str(ANILIST_DIR / "anilistUpdater.py"), "--deps"])
    if ok:
        say("both already import from vendor/, nothing to do")
        return

    if not confirm("Install them? (skip if you do not use AniList)", back=True):
        _skipped.append("AniList packages: run `just setup` later")
        return

    tool = "uv" if have("uv") else "pip"
    plan(f"install requests and guessit into vendor/ with {tool}", install_anilist_deps)
    FOUND["deps_planned"] = True


def install_anilist_deps() -> None:
    requirements = ANILIST_DIR / "requirements.txt"
    if have("uv"):
        command = ["uv", "pip", "install", "--target", str(VENDOR), "-r", str(requirements)]
    else:
        command = [sys.executable, "-m", "pip", "install", "--target", str(VENDOR), "-r", str(requirements)]

    if not run_cmd(command, cwd=REPO):
        warn("the install failed")
        _skipped.append("AniList packages: run `just setup` once uv or pip works")
        return

    ok, lines = capture([sys.executable, str(ANILIST_DIR / "anilistUpdater.py"), "--deps"])
    for line in lines:
        note(line)
    if not ok:
        _skipped.append("AniList packages are installed but mpv cannot import them")


def stage_anilist_token() -> None:
    stage("AniList token")
    say("Marks each episode watched at 85%. Skip it and every other script still")
    say("works; only the n panel and CTRL+n go quiet.")
    print()

    if os.name != "nt":
        warn("the token store uses Windows CryptProtectData, so this stage is Windows-only")
        _skipped.append("AniList token: no token store outside Windows")
        return

    if not confirm("Link an AniList account now?", back=True):
        _skipped.append("AniList token: press CTRL+n in mpv when you want it")
        return

    open_url(ANILIST_AUTH)
    step("Authorize the app. AzuredBlue's public client id is already in that URL.")
    step("AniList then shows the token on the page. Copy the whole thing.")
    note("It is one long line. Nothing is echoed back but its length.")
    token = ask_secret("ANILIST_TOKEN", "Paste the token:")
    if not token:
        warn("nothing pasted")
        _skipped.append("AniList token: press CTRL+n in mpv when you want it")
        return

    note("Held in memory until the receipt is confirmed, and never shown.")
    plan("link the AniList account with the token you pasted", lambda: link_anilist(token))


def link_anilist(token: str) -> None:
    # Over stdin, never argv: the token must stay out of the process list.
    ok, lines = capture(
        [sys.executable, str(ANILIST_DIR / "anilistUpdater.py"), "--setup"],
        stdin_text=token,
    )
    # Only the script's own verdict lines get printed, so nothing can echo back.
    for line in lines:
        if line.startswith(("LINKED:", "ERROR:")):
            note(line)
    if ok:
        print(f"  {GOOD}{OK_MARK} stored{RESET} encrypted under %LOCALAPPDATA%\\mpv-anilist")
        note("Tied to this Windows account, so a copy is inert elsewhere.")
        note("AniList tokens last a year; the panel tells you when to redo this.")
    else:
        warn("AniList would not accept it")
        _skipped.append("AniList token: retry with CTRL+n in mpv")


def stage_install() -> None:
    stage("Install the config")
    say("mpv reads portable_config/ from beside its own executable.")
    print()

    home = FOUND["home"]
    if home is None:
        warn("no install folder, so there is nowhere to copy to")
        note(f"copy {CONFIG} next to your mpv.exe by hand")
        _skipped.append(f"copy {CONFIG} next to mpv.exe")
        return

    dest = home / "portable_config"
    if dest.resolve() == CONFIG.resolve():
        say(f"mpv reads {CONFIG} where it already sits, so there is nothing to copy.")
        note("Every later edit to the repo is live the next time mpv starts.")
        FOUND["installed"] = dest
        return

    say("Everything above lands in this repo first, then gets copied across.")
    say(f"from {CONFIG}")
    say(f"to   {dest}")
    if dest.exists():
        warn("that folder already exists; files with the same name get overwritten")
    plan(f"copy portable_config/ to {dest}", lambda: copy_config(dest))


def copy_config(dest: Path) -> None:
    try:
        # A stale shader cache and this machine's log are no use to a new install.
        shutil.copytree(
            CONFIG,
            dest,
            dirs_exist_ok=True,
            ignore=shutil.ignore_patterns("cache", "*.log", "__pycache__"),
        )
    except OSError as error:
        warn(f"copy failed: {error}")
        note("A folder under Program Files needs an elevated shell.")
        _skipped.append(f"copy {CONFIG} {TO} {dest}")
        return
    print(f"  {GOOD}{OK_MARK} copied{RESET} the config {TO} {dest}")
    note("Repo edits do not reach mpv until you copy again.")
    FOUND["installed"] = dest


def verify() -> None:
    """After everything is applied: how to tell it worked, and an offer to launch."""
    mpv, installed = FOUND["mpv"], FOUND["installed"]
    if mpv is None or installed is None:
        return

    print(f"\n{BOLD}{ACCENT}{STAGE_MARK} Verify{RESET}\n")
    # An mpv from elsewhere ignores a portable_config it is not sitting next to.
    borrowed = mpv.parent != installed.parent
    command = [str(mpv), f"--config-dir={installed}"] if borrowed else [str(mpv)]
    if borrowed:
        say(f"{mpv} lives elsewhere, so it needs the config pointed out to it:")
        note(f'mpv --config-dir="{installed}"')
        print()

    say("Open any video, then:")
    step("F6  - the keyboard map. Every key drawn means input.conf loaded.")
    step("TAB - the uosc interface. A timeline means uosc loaded and patched.")
    step("F4  - the subtitle index. Needs ffmpeg and a subtitle track.")
    print()
    note(f"mpv writes its log to {installed / 'mpv.log'} if something is missing.")
    print()
    if confirm("Launch mpv now to try it?"):
        try:
            subprocess.Popen(command, cwd=str(mpv.parent))
        except OSError as error:
            warn(f"could not launch mpv: {error}")


def main() -> None:
    banner("moonlight-mpv first run")
    run_stages(
        [
            stage_prerequisites,
            stage_uosc,
            stage_patch,
            stage_shaders,
            stage_layout,
            stage_anilist_deps,
            stage_anilist_token,
            stage_install,
            receipt,
        ]
    )
    if _approved:
        apply()
        verify()
    else:
        note("nothing was changed")
    finish()


if __name__ == "__main__":
    run(main)

